---
title: "Portland Housing Price Prediction by Neighborhood"
output:
  html_document: default
  html_notebook: default
Author: 'Team Redfin: Wendy Lally, Cody Miller, Andrew Perigault Monte, Stephan Hoo-fatt,
  Jerrod Thomas'
---
```{r}
#Load library and suppress warnings
suppressWarnings(suppressMessages(library(dplyr)))
#library(dplyr)
suppressWarnings(suppressMessages(library(fpp)))
suppressWarnings(suppressMessages(library(forecast)))
```

```{r child = 'Redfin-Report-Beginning.Rmd'}
```
```{r load-filter-data}
# load all redfin data into the data frame
Oregon.df <- read.csv("Redfin Data Portland_ All Residential_filtered.csv")

#Select and summarize only the home variables
selected.var <-c(2, 6, 9, 24, 27, 30, 39)
Home_data.df = Oregon.df[, selected.var]
print("Relevent Housing variables summary")
summary(Home_data.df)

#Select and summarize only the time variables 
selected.var <-c(33, 34, 35)
Time_data.df = Oregon.df[, selected.var]
print("Relevent Time variables summary")
summary(Time_data.df)

#Select and summarize only the time variables 
selected.var <-c(40, 41, 45)
Time_data.df = Oregon.df[, selected.var]
print("Relavent Location variables summary")
summary(Time_data.df)

# filter to just neighborhood records - the full set has by zipcode, and other breakdowns we don't care about
neighborhoods.df <- Oregon.df[Oregon.df$Region.Type == "neighborhood",]

# load the training data list of unique neighborhoods into an array for iteration
 neighborhoods.array <- unique(neighborhoods.df$Region, incomparables = FALSE)

```

```{r}

# filter to just neighborhood records - the full set has by zipcode, and other breakdowns we don't care about
neighborhoods.df <- Oregon.df[Oregon.df$Region.Type == "neighborhood",]

# load the training data list of unique neighborhoods into an array for iteration
 neighborhoods.array <- unique(neighborhoods.df$Region, incomparables = FALSE)

##Neighborhood Time Series Graphs
```

```{r}
# Create a storage array for our results
neighborhoodsSummary.array <- array()

#We want to store: neighborhood name, timeseries
neighborhoodsSummary.array <- c("")
```

#```{r child = 'Redfin-Report-ForLoop.Rmd'}
#```

```{r}
# For loop
#loop through all the neighboorhoods and for each create a timeseries and print the plot
for (neighborhood in neighborhoods.array){
# use if just want to look at one neighborhood: for (neighborhood in c("Portland, OR - Rose City Park")){
  #select a neighborhood into a dataframe
  oneNeighborhood.df <- neighborhoods.df[Oregon.df$Region == neighborhood,]
  
  #filter out the observations for months that aren't January (1), April (4), July (7), October (10). 
  #Note that had to invert, so selected ones that did not have these patterns matched.
  oneNeighborhood.df<-oneNeighborhood.df[grep("2/|3/|5/|6/|8/|9/|11/|12/", oneNeighborhood.df$Period.Begin, invert = TRUE),]
  # somehow they are out of order, now to sort the period.begin
  oneNeighborhood.df <- oneNeighborhood.df[order(as.Date(oneNeighborhood.df$Period.Begin, format="%m/%d/%Y")),]
  dat1 <- oneNeighborhood.df # save for debugging prior to removing columns
  
  #log how many rows each neighborhood has available
  #cat(neighborhood, " has ", nrow(oneNeighborhood.df), " rows. \n")
  
  # select the median price column for the timeseries
  oneNeighborhood.df <- oneNeighborhood.df[c(18)]
  
  # create the timeseries
  oneNeighborhood.timeseries <- ts(oneNeighborhood.df, frequency=4, start=c(2012,1))
  
  #str(oneNeighborhood.timeseries)
  
  # divide the timeseries that was created into two parts
  trainingData = window(oneNeighborhood.timeseries, start=c(2012,1), end=c(2015,4)) ### Training set (4 years, quarterly data)
  testData = window(oneNeighborhood.timeseries, start=c(2016,1), end=c(2017,4), frequency=4)  ### Test set    (2 years, quarterly data)
  
  # Generic plot of timeseries without any modeling ---------------------
  # plot and set title to the appropriate heading
  options(scipen=999)
  plot(oneNeighborhood.timeseries, main=neighborhood)
  
  
  # Seasonal Naive Plots --------------------------------------------------
  
  # train on data from 2012 to the end of 2015, Forecast for four more years (2016 through 2019)
  snaive.forecast <- snaive(trainingData, h = 16 )

  # Forecast plot for Seasonal Naive ---------
  plotTitle <- paste(neighborhood, ": Naive Model Forecast")
  options(scipen=999)
  # plots both the train data, test data and prediction
  plot(snaive.forecast, main=plotTitle, ylab = "Median House Price", xlab = "Year") 
  lines(testData, col="red") # color the test data to tell it from the train data
  legend("topleft",lty=1,bty = "n",col=c("black", "red","blue"),c("Train Data", "Test Data","Seasonal Naive"))

  # Plot Seasonal Naive Accuracy ---------
  snaive.accuracy <- accuracy(snaive.forecast,testData)
  options(scipen=999)
  tsdisplay(residuals(snaive.forecast), main = paste(plotTitle, " Residuals"))
  
  # Holt Winters Plots -----------------------------------------------------
  
    # Apply Forecasting Method to timeseries - Holt Winters Method
  hwinters.forecast <- forecast(HoltWinters(trainingData), h = 16)

  # Forecast plot for Holt Winters ---------
  plotTitle <- paste(neighborhood, ": Holt Winters Model Forecast")
  options(scipen=999)
  # plots both the train data, test data and prediction
  plot(hwinters.forecast, main=plotTitle, ylab = "Median House Price", xlab = "Year") 
  lines(testData, col="red") # color the test data to tell it from the train data
  legend("topleft",lty=1,bty = "n",col=c("black", "red","blue"),c("Train Data", "Test Data","Holt Winters"))

  # Plot Holt Winters Accuracy ---------
  hwinters.accuracy <- accuracy(hwinters.forecast,testData)
  options(scipen=999)
  tsdisplay(residuals(hwinters.forecast), main = paste(plotTitle, " Residuals"))

  # Compare Accuracy --------------------------------------------------------
  print("Accuracy for Seasonal and Holt Winters")
  # Seasonal Naive
  snaive.accuracy
  # Holt Winters
  hwinters.accuracy
  

  # Forecast plot for Combined models ---------
  print("Combined models plotting")
  plotTitle <- paste(neighborhood, ": TS Models Comparison")
  options(scipen=999)
  print("plot combined")
  # plots both the train data, test data and both predictions
  plot(hwinters.forecast$mean, main=plotTitle, ylab = "Median House Price", xlab = "Year", lty="dashed") 
  lines(snaive.forecast$mean, col="green", lty="dashed")
  lines(testData, col="red") # color the test data to tell it from the train data
  lines(trainingData, col="black") # color the train data
  print("legend")
  legend("topleft",lty=1,bty = "n",col=c("black", "red","blue", "green"),c("Train Data", "Test Data","Holt Winters", "Seasonal Naive"))

  
  
}
```

#```{r child = 'Redfin-Report-PracticePlotting.Rmd'}
#```

#```{r child = 'Redfin-Report-Naive.Rmd'}
#```
#```{r child = 'Redfin-Report-Seasonal-Naive.Rmd'}
#```

#```{r child = 'Redfin-Report-Drift.Rmd'}
#```

#```{r child = 'Redfin-Report-HoltWinters.Rmd'}
#```

